name: csi-node-driver-registrar

on:
  push:
    paths:
      - '.github/workflows/csi-node-driver-registrar.yml'
      - 'build/csi-node-driver-registrar/**'
      - '!build/csi-node-driver-registrar/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/csi-node-driver-registrar/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-node-driver-registrar:${{ github.sha }} \
            -f ./build/csi-node-driver-registrar/Dockerfile \
            ./build/csi-node-driver-registrar/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-node-driver-registrar:latest \
            --tag raspbernetes/csi-node-driver-registrar:${{ env.VERSION }} \
            --tag k8sathome/csi-node-driver-registrar:${{ env.VERSION }} \
            -f ./build/csi-node-driver-registrar/Dockerfile \
            ./build/csi-node-driver-registrar/ \
            --push
