name: csi-external-provisioner

on:
  push:
    paths:
      - '.github/workflows/csi-external-provisioner.yml'
      - 'build/csi-external-provisioner/**'
      - '!build/csi-external-provisioner/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/csi-external-provisioner/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-external-provisioner:${{ github.sha }} \
            -f ./build/csi-external-provisioner/Dockerfile \
            ./build/csi-external-provisioner/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-external-provisioner:latest \
            --tag raspbernetes/csi-external-provisioner:${{ env.VERSION }} \
            --tag k8sathome/csi-external-provisioner:${{ env.VERSION }} \
            -f ./build/csi-external-provisioner/Dockerfile \
            ./build/csi-external-provisioner/ \
            --push
