name: csi-external-resizer

on:
  push:
    paths:
      - '.github/workflows/csi-external-resizer.yml'
      - 'build/csi-external-resizer/**'
      - '!build/csi-external-resizer/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/csi-external-resizer/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-external-resizer:${{ github.sha }} \
            --file ./build/csi-external-resizer/Dockerfile \
            ./build/csi-external-resizer/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/csi-external-resizer:latest \
            --tag raspbernetes/csi-external-resizer:${{ env.VERSION }} \
            --tag k8sathome/csi-external-resizer:${{ env.VERSION }} \
            --file ./build/csi-external-resizer/Dockerfile \
            ./build/csi-external-resizer/ \
            --output "type=image,push=true"
