name: cstor-pool-arm64

on:
  push:
    paths:
      - '.github/workflows/cstor-pool-arm64.yml'
      - 'build/cstor-pool-arm64/**'
      - '!build/cstor-pool-arm64/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/cstor-pool-arm64/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker build \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/cstor-pool-arm64:${{ github.sha }} \
            -f ./build/cstor-pool-arm64/Dockerfile \
            ./build/cstor-pool-arm64/

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker build \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/cstor-pool-arm64:latest \
            --tag raspbernetes/cstor-pool-arm64:${{ env.VERSION }} \
            -f ./build/cstor-pool-arm64/Dockerfile \
            ./build/cstor-pool-arm64/

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker push \
          raspbernetes/cstor-pool-arm64:${{ github.sha }}

      - name: Push Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker push \
          raspbernetes/cstor-pool-arm64:latest \
          raspbernetes/cstor-pool-arm64:${{ env.VERSION }}
