name: external-dns

on:
  push:
    paths:
      - '.github/workflows/external-dns.yml'
      - 'build/external-dns/**'
      - '!build/external-dns/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/external-dns/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64\
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/external-dns:${{ github.sha }} \
            --file ./build/external-dns/Dockerfile \
            ./build/external-dns/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/external-dns:latest \
            --tag raspbernetes/external-dns:${{ env.VERSION }} \
            --file ./build/external-dns/Dockerfile \
            ./build/external-dns/ \
            --output "type=image,push=true"
