name: fluxd

on:
  push:
    paths:
      - 'build/fluxd/**'
      - '!build/fluxd/*.md'
  pull_request:
    paths:
      - 'build/fluxd/**'
      - '!build/fluxd/*.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/fluxd/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/fluxd:${{ env.VERSION }} \
            --tag k8sathome/fluxd:${{ env.VERSION }} \
            -f ./build/fluxd/Dockerfile \
            --push ./build/fluxd/
