name: gatekeeper

on:
  push:
    paths:
      - 'build/gatekeeper/**'
      - '!build/gatekeeper/*.md'
  pull_request:
    paths:
      - 'build/gatekeeper/**'
      - '!build/gatekeeper/*.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/gatekeeper/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag raspbernetes/gatekeeper:${{ github.sha }} \
            -f ./build/gatekeeper/Dockerfile \
            --push ./build/gatekeeper/

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag raspbernetes/gatekeeper:${{ env.VERSION }} \
            --tag k8sathome/gatekeeper:${{ env.VERSION }} \
            -f ./build/gatekeeper/Dockerfile \
            --push ./build/gatekeeper/
