name: helm-operator

on:
  push:
    paths:
      - '.github/workflows/helm-operator.yml'
      - 'build/helm-operator/**'
      - '!build/helm-operator/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/helm-operator/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/helm-operator:${{ github.sha }} \
            --file ./build/helm-operator/Dockerfile \
            --output "type=image,push=true" ./build/helm-operator/

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/helm-operator:latest \
            --tag raspbernetes/helm-operator:${{ env.VERSION }} \
            --tag k8sathome/helm-operator:${{ env.VERSION }} \
            --file ./build/helm-operator/Dockerfile \
            --output "type=image,push=true" ./build/helm-operator/
