name: istio-operator

on:
  push:
    paths:
      - '.github/workflows/istio-operator.yml'
      - 'build/istio-operator/**'
      - '!build/istio-operator/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/istio-operator/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-operator:${{ github.sha }} \
            --file ./build/istio-operator/Dockerfile \
            ./build/istio-operator/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag k8sathome/istio-operator:latest \
            --tag raspbernetes/istio-operator:${{ env.VERSION }} \
            --tag k8sathome/istio-operator:${{ env.VERSION }} \
            --file ./build/istio-operator/Dockerfile \
            ./build/istio-operator/ \
            --output "type=image,push=true"
