name: istio-proxyv2

on:
  push:
    paths:
      - '.github/workflows/istio-proxyv2.yml'
      - 'build/istio-proxyv2/**'
      - '!build/istio-proxyv2/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    env:
      VERSION: $(cat build/istio-proxyv2/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-proxyv2:${{ github.sha }} \
            --file ./build/istio-proxyv2/Dockerfile \
            ./build/istio-proxyv2/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-proxyv2:latest \
            --tag raspbernetes/istio-proxyv2:${{ env.VERSION }} \
            --file ./build/istio-proxyv2/Dockerfile \
            ./build/istio-proxyv2/ \
            --output "type=image,push=true"
