name: istio-pilot

on:
  push:
    paths:
      - '.github/workflows/istio-pilot.yml'
      - 'build/istio-pilot/**'
      - '!build/istio-pilot/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    env:
      VERSION: $(cat build/istio-pilot/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-pilot:${{ github.sha }} \
            --file ./build/istio-pilot/Dockerfile \
            ./build/istio-pilot/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/istio-pilot:latest \
            --tag raspbernetes/istio-pilot:${{ env.VERSION }} \
            --file ./build/istio-pilot/Dockerfile \
            ./build/istio-pilot/ \
            --output "type=image,push=true"
