name: kubectl

on:
  push:
    paths:
      - '.github/workflows/kubectl.yml'
      - 'build/kubectl/**'
      - '!build/kubectl/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/kubectl/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/kubectl:${{ github.sha }} \
            --file ./build/kubectl/Dockerfile \
            ./build/kubectl/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/kubectl:latest \
            --tag raspbernetes/kubectl:${{ env.VERSION }} \
            --tag k8sathome/kubectld:${{ env.VERSION }} \
            --file ./build/kubectl/Dockerfile \
            ./build/kubectl/ \
            --output "type=image,push=true"
