name: kube-bench

on:
  push:
    paths:
      - '.github/workflows/kube-bench.yml'
      - 'build/kube-bench/**'
      - '!build/kube-bench/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/kube-bench/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg BUILD_DATE=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(shell git rev-parse --short HEAD) \
            --tag raspbernetes/kube-bench:${{ github.sha }} \
            --file ./build/kube-bench/Dockerfile \
            ./build/kube-bench/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg BUILD_DATE=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(shell git rev-parse --short HEAD) \
            --tag raspbernetes/kube-bench:latest \
            --tag raspbernetes/kube-bench:${{ env.VERSION }} \
            --file ./build/kube-bench/Dockerfile \
            ./build/kube-bench/ \
            --output "type=image,push=true"
