name: kubectl

on:
  push:
    paths:
      - '.github/workflows/kubectl.yml'
      - 'build/kubectl/**'
      - '!build/kubectl/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/kubectl/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/kubectl:${{ github.sha }} \
            -f ./build/kubectl/Dockerfile \
            ./build/kubectl/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/kubectl:latest \
            --tag raspbernetes/kubectl:${{ env.VERSION }} \
            --tag k8sathome/kubectld:${{ env.VERSION }} \
            -f ./build/kubectl/Dockerfile \
            ./build/kubectl/ \
            --push
