name: prometheus-operator

on:
  push:
    paths:
      - '.github/workflows/prometheus-operator.yml'
      - 'build/prometheus-operator/**'
      - '!build/prometheus-operator/*.md'

jobs:
  build:
    env:
      VERSION: $(cat build/prometheus-operator/.version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/prometheus-operator:${{ github.sha }} \
            -f ./build/prometheus-operator/Dockerfile \
            ./build/prometheus-operator/ \
            --push

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/prometheus-operator:latest \
            --tag raspbernetes/prometheus-operator:${{ env.VERSION }} \
            --tag k8sathome/prometheus-operator:${{ env.VERSION }} \
            -f ./build/prometheus-operator/Dockerfile \
            ./build/prometheus-operator/ \
            --push
