name: sops

on:
  push:
    paths:
      - '.github/workflows/sops.yml'
      - 'build/sops/**'
      - '!build/sops/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/sops/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Container Image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/sops:${{ github.sha }} \
            --file ./build/sops/Dockerfile \
            ./build/sops/ \
            --output "type=image,push=true"

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --tag raspbernetes/sops:latest \
            --tag raspbernetes/sops:${{ env.VERSION }} \
            --tag k8sathome/sops:${{ env.VERSION }} \
            --file ./build/sops/Dockerfile \
            ./build/sops/ \
            --output "type=image,push=true"
